apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../base/applications/monitoring

patches: [] # define here the changes you want on this environment compared to the base
